pipeline {
    agent any

    environment {
        DOCKER_IMAGE_BACKEND = "007kumar/backend:latest"
        DOCKER_IMAGE_FRONTEND = "007kumar/frontend:latest"
        KUBERNETES_NAMESPACE = "mern-app"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/007kumar/mern-deployment.git'
            }
        }

        stage('Build Backend Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE_BACKEND .'
            }
        }

        stage('Push Backend Docker Image') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh 'docker push $DOCKER_IMAGE_BACKEND'
                }
            }
        }

        stage('Deploy Backend to Kubernetes') {
            steps {
                sh '''
                kubectl apply -f backend-deployment.yaml
                kubectl apply -f backend-service.yaml
                '''
            }
        }

        stage('Checkout Frontend Code') {
            steps {
                git 'https://github.com/007kumar/mern-deployment.git'
            }
        }

        stage('Build Frontend Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE_FRONTEND .'
            }
        }

        stage('Push Frontend Docker Image') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh 'docker push $DOCKER_IMAGE_FRONTEND'
                }
            }
        }

        stage('Deploy Frontend to Kubernetes') {
            steps {
                sh '''
                kubectl apply -f frontend-deployment.yaml
                kubectl apply -f frontend-service.yaml
                '''
            }
        }

        stage('Deploy Using HELM') {
            steps {
                sh '''
                helm upgrade --install my-mern-app ./mern-chart
                '''
            }
        }
    }
}
