apiVersion: v1
kind: Service
metadata:
  name: backend-service-v2
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000  # Exposed service port
      targetPort: 5000  # Backend container's port
  type: ClusterIP  # Internal service only

