apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2  # Number of backend pods
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 007kumar/backend:latest  # Replace with your Docker image
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://ShivBatch8:Mongopass@shiv.bh0ao.mongodb.net/?retryWrites=true&w=majority&appName=shiv"
