apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017  # Exposed service port
      targetPort: 27017  # MongoDB container's port
  type: ClusterIP  # Internal service only

